import { GovernmentProgram } from '@/types/program'

export const sampleScholarships: GovernmentProgram[] = [
    {
        id: 'sch-1',
        title: 'HEC Indigenous Scholarship Program',
        title_urdu: 'ایچ ای سی انڈیجینس اسکالرشپ پروگرام',
        description: 'Scholarships for MS/MPhil and PhD students in Pakistani universities.',
        description_urdu: 'پاکستانی جامعات میں ایم ایس/ایم فل اور پی ایچ ڈی طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Monthly stipend', 'Research grant'],
        benefits_urdu: ['مکمل فیس', 'ماہانہ وظیفہ', 'ریسرچ گرانٹ'],
        application_deadline: '2024-09-30',
        application_url: 'https://hec.gov.pk/english/scholarshipsgrants/indigenous',
        contact_info: { website: 'https://hec.gov.pk' },
        requirements: ['Admission in MS/MPhil/PhD', 'Pakistani nationality'],
        requirements_urdu: ['ایم ایس/ایم فل/پی ایچ ڈی میں داخلہ', 'پاکستانی شہریت'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '2-5 years',
        location: ['Pakistan'],
        age_range: { min: 18, max: 35 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-2',
        title: 'Punjab Educational Endowment Fund (PEEF) Scholarship',
        title_urdu: 'پنجاب ایجوکیشنل انڈومنٹ فنڈ اسکالرشپ',
        description: 'Merit and need-based scholarships for students of Punjab at intermediate, graduation, and master levels.',
        description_urdu: 'پنجاب کے طلباء کے لیے میرٹ اور ضرورت پر مبنی وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['high_school', 'bachelor', 'master'], location: ['Punjab'] },
        benefits: ['Tuition fee', 'Monthly stipend'],
        benefits_urdu: ['فیس', 'ماہانہ وظیفہ'],
        application_deadline: '2024-10-15',
        application_url: 'https://peef.org.pk',
        contact_info: { website: 'https://peef.org.pk' },
        requirements: ['Punjab domicile', 'Merit/need criteria'],
        requirements_urdu: ['پنجاب ڈومیسائل', 'میرٹ/ضرورت معیار'],
        funding_amount: { min: 20000, max: 100000, currency: 'PKR' },
        duration: '1-4 years',
        location: ['Punjab'],
        age_range: { min: 15, max: 28 },
        education_level: ['high_school', 'bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-3',
        title: 'Ehsaas Undergraduate Scholarship',
        title_urdu: 'احساس انڈرگریجویٹ اسکالرشپ',
        description: 'Need-based scholarships for undergraduate students in public sector universities.',
        description_urdu: 'سرکاری جامعات کے انڈرگریجویٹ طلباء کے لیے ضرورت پر مبنی وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Annual stipend'],
        benefits_urdu: ['مکمل فیس', 'سالانہ وظیفہ'],
        application_deadline: '2024-11-01',
        application_url: 'https://ehsaas.hec.gov.pk',
        contact_info: { website: 'https://ehsaas.hec.gov.pk' },
        requirements: ['Enrolled in public university', 'Low income family'],
        requirements_urdu: ['سرکاری جامعہ میں داخلہ', 'کم آمدنی والا خاندان'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '4 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor'],
        income_level: ['low'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-4',
        title: 'Sindh Endowment Fund Scholarship',
        title_urdu: 'سندھ انڈومنٹ فنڈ اسکالرشپ',
        description: 'Scholarships for students of Sindh studying in reputable institutions.',
        description_urdu: 'سندھ کے طلباء کے لیے معروف اداروں میں تعلیم کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Sindh'] },
        benefits: ['Tuition fee', 'Stipend'],
        benefits_urdu: ['فیس', 'وظیفہ'],
        application_deadline: '2024-09-15',
        application_url: 'https://sindh.gov.pk/endowment',
        contact_info: { website: 'https://sindh.gov.pk/endowment' },
        requirements: ['Sindh domicile', 'Admission in listed institution'],
        requirements_urdu: ['سندھ ڈومیسائل', 'درج شدہ ادارے میں داخلہ'],
        funding_amount: { min: 30000, max: 150000, currency: 'PKR' },
        duration: '1-4 years',
        location: ['Sindh'],
        age_range: { min: 17, max: 30 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-5',
        title: 'Balochistan Education Endowment Fund (BEEF) Scholarship',
        title_urdu: 'بلوچستان ایجوکیشن انڈومنٹ فنڈ اسکالرشپ',
        description: 'Merit and need-based scholarships for students of Balochistan.',
        description_urdu: 'بلوچستان کے طلباء کے لیے میرٹ اور ضرورت پر مبنی وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['high_school', 'bachelor', 'master'], location: ['Balochistan'] },
        benefits: ['Tuition fee', 'Stipend'],
        benefits_urdu: ['فیس', 'وظیفہ'],
        application_deadline: '2024-10-10',
        application_url: 'https://beef.org.pk',
        contact_info: { website: 'https://beef.org.pk' },
        requirements: ['Balochistan domicile', 'Merit/need criteria'],
        requirements_urdu: ['بلوچستان ڈومیسائل', 'میرٹ/ضرورت معیار'],
        funding_amount: { min: 20000, max: 100000, currency: 'PKR' },
        duration: '1-4 years',
        location: ['Balochistan'],
        age_range: { min: 15, max: 28 },
        education_level: ['high_school', 'bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-6',
        title: 'Khyber Pakhtunkhwa (KPK) Scholarship Program',
        title_urdu: 'خیبر پختونخوا اسکالرشپ پروگرام',
        description: 'Scholarships for students of KPK at various education levels.',
        description_urdu: 'خیبر پختونخوا کے طلباء کے لیے مختلف تعلیمی سطحوں پر وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['high_school', 'bachelor', 'master'], location: ['KPK'] },
        benefits: ['Tuition fee', 'Stipend'],
        benefits_urdu: ['فیس', 'وظیفہ'],
        application_deadline: '2024-10-20',
        application_url: 'https://khyberpakhtunkhwa.gov.pk/scholarships',
        contact_info: { website: 'https://khyberpakhtunkhwa.gov.pk/scholarships' },
        requirements: ['KPK domicile', 'Merit/need criteria'],
        requirements_urdu: ['کے پی کے ڈومیسائل', 'میرٹ/ضرورت معیار'],
        funding_amount: { min: 20000, max: 100000, currency: 'PKR' },
        duration: '1-4 years',
        location: ['KPK'],
        age_range: { min: 15, max: 28 },
        education_level: ['high_school', 'bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-7',
        title: 'FATA Scholarship Program',
        title_urdu: 'فاٹا اسکالرشپ پروگرام',
        description: 'Scholarships for students from former FATA regions.',
        description_urdu: 'سابقہ فاٹا کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['high_school', 'bachelor'], location: ['FATA'] },
        benefits: ['Tuition fee', 'Stipend'],
        benefits_urdu: ['فیس', 'وظیفہ'],
        application_deadline: '2024-09-25',
        application_url: 'https://fata.gov.pk/scholarships',
        contact_info: { website: 'https://fata.gov.pk/scholarships' },
        requirements: ['FATA domicile', 'Admission in recognized institution'],
        requirements_urdu: ['فاٹا ڈومیسائل', 'تسلیم شدہ ادارے میں داخلہ'],
        funding_amount: { min: 20000, max: 100000, currency: 'PKR' },
        duration: '1-4 years',
        location: ['FATA'],
        age_range: { min: 15, max: 28 },
        education_level: ['high_school', 'bachelor'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-8',
        title: 'USAID Merit and Needs Based Scholarship',
        title_urdu: 'یو ایس ایڈ میرٹ اینڈ نیڈ بیسڈ اسکالرشپ',
        description: 'Scholarships for financially disadvantaged students in partner universities.',
        description_urdu: 'شریک جامعات میں مالی طور پر کمزور طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Stipend'],
        benefits_urdu: ['مکمل فیس', 'وظیفہ'],
        application_deadline: '2024-11-10',
        application_url: 'https://hec.gov.pk/english/scholarshipsgrants/USAID',
        contact_info: { website: 'https://hec.gov.pk/english/scholarshipsgrants/USAID' },
        requirements: ['Enrolled in partner university', 'Low income family'],
        requirements_urdu: ['شریک جامعہ میں داخلہ', 'کم آمدنی والا خاندان'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '4 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor'],
        income_level: ['low'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-9',
        title: 'National ICT R&D Fund Scholarship',
        title_urdu: 'نیشنل آئی سی ٹی آر اینڈ ڈی فنڈ اسکالرشپ',
        description: 'Scholarships for undergraduate students in ICT-related fields.',
        description_urdu: 'آئی سی ٹی سے متعلق شعبوں میں انڈرگریجویٹ طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Stipend'],
        benefits_urdu: ['مکمل فیس', 'وظیفہ'],
        application_deadline: '2024-09-20',
        application_url: 'https://ignite.org.pk/scholarships',
        contact_info: { website: 'https://ignite.org.pk/scholarships' },
        requirements: ['Enrolled in ICT program', 'Pakistani nationality'],
        requirements_urdu: ['آئی سی ٹی پروگرام میں داخلہ', 'پاکستانی شہریت'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '4 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-10',
        title: 'Pakistan Bait-ul-Mal Scholarship',
        title_urdu: 'پاکستان بیت المال اسکالرشپ',
        description: 'Financial assistance for deserving students at all education levels.',
        description_urdu: 'تمام تعلیمی سطحوں پر مستحق طلباء کے لیے مالی امداد۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['primary', 'secondary', 'high_school', 'bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Stipend'],
        benefits_urdu: ['فیس', 'وظیفہ'],
        application_deadline: '2024-12-01',
        application_url: 'https://baitulmal.gov.pk',
        contact_info: { website: 'https://baitulmal.gov.pk' },
        requirements: ['Pakistani nationality', 'Deserving student'],
        requirements_urdu: ['پاکستانی شہریت', 'مستحق طالب علم'],
        funding_amount: { min: 10000, max: 100000, currency: 'PKR' },
        duration: '1-5 years',
        location: ['Pakistan'],
        age_range: { min: 10, max: 35 },
        education_level: ['primary', 'secondary', 'high_school', 'bachelor', 'master'],
        income_level: ['low'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-11',
        title: 'Prime Minister\'s Youth Business Loan Scheme',
        title_urdu: 'وزیر اعظم یوتھ بزنس لون اسکیم',
        description: 'Interest-free loans for young entrepreneurs to start their own businesses.',
        description_urdu: 'نوجوان کاروباریوں کے لیے سود سے پاک قرضے اپنا کاروبار شروع کرنے کے لیے۔',
        category: 'loan',
        eligibility_criteria: { age_min: 21, age_max: 45, education_level: ['high_school', 'bachelor', 'master'], income_level: ['low', 'medium'] },
        benefits: ['Interest-free loan up to Rs. 2 million', 'Business training and mentorship', 'Technical support and guidance'],
        benefits_urdu: ['2 لاکھ روپے تک سود سے پاک قرضہ', 'کاروباری تربیت اور رہنمائی', 'تکنیکی مدد اور رہنمائی'],
        application_deadline: '2024-12-31',
        application_url: 'https://pmyp.gov.pk',
        contact_info: { website: 'https://pmyp.gov.pk' },
        requirements: ['Valid CNIC', 'Business plan', 'Educational certificates', 'Income certificate'],
        requirements_urdu: ['درست شناختی کارڈ', 'کاروباری منصوبہ', 'تعلیمی سرٹیفکیٹ', 'آمدنی کا سرٹیفکیٹ'],
        funding_amount: { min: 100000, max: 2000000, currency: 'PKR' },
        duration: '5 years',
        location: ['Pakistan'],
        age_range: { min: 21, max: 45 },
        education_level: ['high_school', 'bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-12',
        title: 'Skill Development Program for Women',
        title_urdu: 'خواتین کے لیے ہنر کی ترقی کا پروگرام',
        description: 'Free skill training programs for women to enhance employability and entrepreneurship.',
        description_urdu: 'خواتین کے لیے ملازمت اور کاروبار کے لیے مفت ہنر کی تربیت۔',
        category: 'skill_training',
        eligibility_criteria: { age_min: 18, age_max: 50, education_level: ['primary', 'secondary', 'high_school'], gender: 'female' },
        benefits: ['Free training in various skills', 'Job placement assistance', 'Microfinance support', 'Business development training'],
        benefits_urdu: ['مختلف ہنروں میں مفت تربیت', 'ملازمت کی تلاش میں مدد', 'مائیکرو فنانس کی مدد', 'کاروبار کی ترقی کی تربیت'],
        application_deadline: '2024-10-30',
        application_url: 'https://womenempowerment.gov.pk',
        contact_info: { website: 'https://womenempowerment.gov.pk' },
        requirements: ['Valid CNIC', 'Educational certificates', 'Character certificate', 'Passport size photographs'],
        requirements_urdu: ['درست شناختی کارڈ', 'تعلیمی سرٹیفکیٹ', 'کردار کا سرٹیفکیٹ', 'پاسپورٹ سائز کی تصاویر'],
        funding_amount: { min: 0, max: 50000, currency: 'PKR' },
        duration: '6 months',
        location: ['Pakistan'],
        age_range: { min: 18, max: 50 },
        education_level: ['primary', 'secondary', 'high_school'],
        gender: 'female',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-13',
        title: 'Prime Minister\'s Kamyab Jawan Program',
        title_urdu: 'وزیر اعظم کام یاب جوان پروگرام',
        description: 'Youth entrepreneurship and skill development program with financial support.',
        description_urdu: 'نوجوانوں کے کاروبار اور ہنر کی ترقی کا پروگرام مالی مدد کے ساتھ۔',
        category: 'business',
        eligibility_criteria: { age_min: 18, age_max: 45, education_level: ['high_school', 'bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Interest-free loans', 'Skill training', 'Mentorship', 'Business development support'],
        benefits_urdu: ['سود سے پاک قرضے', 'ہنر کی تربیت', 'رہنمائی', 'کاروبار کی ترقی کی مدد'],
        application_deadline: '2024-11-30',
        application_url: 'https://kamyaabjawan.gov.pk',
        contact_info: { website: 'https://kamyaabjawan.gov.pk' },
        requirements: ['Valid CNIC', 'Business plan', 'Educational certificates'],
        requirements_urdu: ['درست شناختی کارڈ', 'کاروباری منصوبہ', 'تعلیمی سرٹیفکیٹ'],
        funding_amount: { min: 100000, max: 5000000, currency: 'PKR' },
        duration: '3-7 years',
        location: ['Pakistan'],
        age_range: { min: 18, max: 45 },
        education_level: ['high_school', 'bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-14',
        title: 'HEC Overseas Scholarship Program',
        title_urdu: 'ایچ ای سی اوورسیز اسکالرشپ پروگرام',
        description: 'Scholarships for Pakistani students to study abroad in selected countries.',
        description_urdu: 'پاکستانی طلباء کے لیے منتخب ممالک میں بیرون ملک تعلیم کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Living allowance', 'Airfare', 'Health insurance'],
        benefits_urdu: ['مکمل فیس', 'رہائشی الاؤنس', 'ہوائی کرایہ', 'صحت کی بیمہ'],
        application_deadline: '2024-08-01',
        application_url: 'https://hec.gov.pk/english/scholarshipsgrants/overseas',
        contact_info: { website: 'https://hec.gov.pk' },
        requirements: ['Pakistani nationality', 'Excellent academic record', 'IELTS/TOEFL score'],
        requirements_urdu: ['پاکستانی شہریت', 'بہترین تعلیمی ریکارڈ', 'آئی ای ایل ٹی ایس/ٹوفل سکور'],
        funding_amount: { min: 500000, max: 5000000, currency: 'PKR' },
        duration: '2-4 years',
        location: ['Pakistan'],
        age_range: { min: 20, max: 35 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-15',
        title: 'Pakistan Software Export Board (PSEB) Training Program',
        title_urdu: 'پاکستان سافٹ ویئر ایکسپورٹ بورڈ تربیتی پروگرام',
        description: 'Free IT training programs for youth to enter the software industry.',
        description_urdu: 'نوجوانوں کے لیے سافٹ ویئر انڈسٹری میں داخلے کے لیے مفت آئی ٹی تربیت۔',
        category: 'skill_training',
        eligibility_criteria: { age_min: 18, age_max: 35, education_level: ['high_school', 'bachelor'], location: ['Pakistan'] },
        benefits: ['Free IT training', 'Job placement', 'Industry certification', 'Internship opportunities'],
        benefits_urdu: ['مفت آئی ٹی تربیت', 'ملازمت کی فراہمی', 'انڈسٹری سرٹیفیکیشن', 'انٹرن شپ کے مواقع'],
        application_deadline: '2024-09-15',
        application_url: 'https://pseb.org.pk',
        contact_info: { website: 'https://pseb.org.pk' },
        requirements: ['Valid CNIC', 'Educational certificates', 'Basic computer knowledge'],
        requirements_urdu: ['درست شناختی کارڈ', 'تعلیمی سرٹیفکیٹ', 'بنیادی کمپیوٹر کا علم'],
        funding_amount: { min: 0, max: 100000, currency: 'PKR' },
        duration: '3-6 months',
        location: ['Pakistan'],
        age_range: { min: 18, max: 35 },
        education_level: ['high_school', 'bachelor'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-16',
        title: 'National Vocational and Technical Training Commission (NAVTTC) Program',
        title_urdu: 'نیشنل ووکیشنل اینڈ ٹیکنیکل ٹریننگ کمیشن پروگرام',
        description: 'Technical and vocational training programs for skill development.',
        description_urdu: 'ہنر کی ترقی کے لیے تکنیکی اور پیشہ ورانہ تربیتی پروگرام۔',
        category: 'skill_training',
        eligibility_criteria: { age_min: 16, age_max: 40, education_level: ['primary', 'secondary', 'high_school'], location: ['Pakistan'] },
        benefits: ['Free technical training', 'Certification', 'Job placement assistance', 'Tool kit'],
        benefits_urdu: ['مفت تکنیکی تربیت', 'سرٹیفیکیشن', 'ملازمت کی فراہمی میں مدد', 'ٹول کٹ'],
        application_deadline: '2024-10-01',
        application_url: 'https://navttc.gov.pk',
        contact_info: { website: 'https://navttc.gov.pk' },
        requirements: ['Valid CNIC', 'Educational certificates', 'Age proof'],
        requirements_urdu: ['درست شناختی کارڈ', 'تعلیمی سرٹیفکیٹ', 'عمر کا ثبوت'],
        funding_amount: { min: 0, max: 50000, currency: 'PKR' },
        duration: '3-12 months',
        location: ['Pakistan'],
        age_range: { min: 16, max: 40 },
        education_level: ['primary', 'secondary', 'high_school'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-17',
        title: 'Pakistan Agricultural Research Council (PARC) Scholarship',
        title_urdu: 'پاکستان ایگریکلچرل ریسرچ کونسل اسکالرشپ',
        description: 'Scholarships for students pursuing agricultural studies and research.',
        description_urdu: 'زرعی تعلیم اور تحقیق کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master', 'phd'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Research grant', 'Stipend', 'Field work support'],
        benefits_urdu: ['فیس', 'ریسرچ گرانٹ', 'وظیفہ', 'فیلڈ ورک کی مدد'],
        application_deadline: '2024-09-30',
        application_url: 'https://parc.gov.pk',
        contact_info: { website: 'https://parc.gov.pk' },
        requirements: ['Agricultural background', 'Research proposal', 'Academic excellence'],
        requirements_urdu: ['زرعی پس منظر', 'ریسرچ پروپوزل', 'تعلیمی برتری'],
        funding_amount: { min: 50000, max: 300000, currency: 'PKR' },
        duration: '2-5 years',
        location: ['Pakistan'],
        age_range: { min: 18, max: 35 },
        education_level: ['bachelor', 'master', 'phd'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-18',
        title: 'Pakistan Council of Scientific and Industrial Research (PCSIR) Program',
        title_urdu: 'پاکستان کونسل آف سائنٹیفک اینڈ انڈسٹریل ریسرچ پروگرام',
        description: 'Research and development opportunities in scientific and industrial fields.',
        description_urdu: 'سائنسی اور صنعتی شعبوں میں تحقیق اور ترقی کے مواقع۔',
        category: 'employment',
        eligibility_criteria: { education_level: ['bachelor', 'master', 'phd'], location: ['Pakistan'] },
        benefits: ['Research opportunities', 'Stipend', 'Professional development', 'Industry exposure'],
        benefits_urdu: ['تحقیق کے مواقع', 'وظیفہ', 'پیشہ ورانہ ترقی', 'انڈسٹری کا تجربہ'],
        application_deadline: '2024-08-15',
        application_url: 'https://pcsir.gov.pk',
        contact_info: { website: 'https://pcsir.gov.pk' },
        requirements: ['Scientific background', 'Research proposal', 'Academic excellence'],
        requirements_urdu: ['سائنسی پس منظر', 'ریسرچ پروپوزل', 'تعلیمی برتری'],
        funding_amount: { min: 30000, max: 150000, currency: 'PKR' },
        duration: '1-3 years',
        location: ['Pakistan'],
        age_range: { min: 20, max: 40 },
        education_level: ['bachelor', 'master', 'phd'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-19',
        title: 'Pakistan Engineering Council (PEC) Training Program',
        title_urdu: 'پاکستان انجینئرنگ کونسل تربیتی پروگرام',
        description: 'Professional development and training programs for engineers.',
        description_urdu: 'انجینئروں کے لیے پیشہ ورانہ ترقی اور تربیتی پروگرام۔',
        category: 'skill_training',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Professional training', 'Certification', 'Continuing education', 'Industry networking'],
        benefits_urdu: ['پیشہ ورانہ تربیت', 'سرٹیفیکیشن', 'مسلسل تعلیم', 'انڈسٹری نیٹ ورکنگ'],
        application_deadline: '2024-09-01',
        application_url: 'https://pec.org.pk',
        contact_info: { website: 'https://pec.org.pk' },
        requirements: ['Engineering degree', 'PEC registration', 'Professional experience'],
        requirements_urdu: ['انجینئرنگ ڈگری', 'پی ای سی رجسٹریشن', 'پیشہ ورانہ تجربہ'],
        funding_amount: { min: 10000, max: 100000, currency: 'PKR' },
        duration: '1-6 months',
        location: ['Pakistan'],
        age_range: { min: 22, max: 50 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium', 'high'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-20',
        title: 'Pakistan Medical and Dental Council (PMDC) Scholarship',
        title_urdu: 'پاکستان میڈیکل اینڈ ڈینٹل کونسل اسکالرشپ',
        description: 'Scholarships for medical and dental students from disadvantaged backgrounds.',
        description_urdu: 'کمزور پس منظر کے طبی اور دانتوں کے ڈاکٹروں کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Stipend', 'Books allowance', 'Clinical training'],
        benefits_urdu: ['فیس', 'وظیفہ', 'کتابوں کا الاؤنس', 'کلینیکل تربیت'],
        application_deadline: '2024-08-20',
        application_url: 'https://pmdc.org.pk',
        contact_info: { website: 'https://pmdc.org.pk' },
        requirements: ['Medical/dental admission', 'Financial need', 'Academic merit'],
        requirements_urdu: ['طبی/دانتوں کے ڈاکٹر کا داخلہ', 'مالی ضرورت', 'تعلیمی میرٹ'],
        funding_amount: { min: 100000, max: 500000, currency: 'PKR' },
        duration: '5 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor'],
        income_level: ['low'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-21',
        title: 'Pakistan Bar Council Scholarship',
        title_urdu: 'پاکستان بار کونسل اسکالرشپ',
        description: 'Scholarships for law students from underprivileged backgrounds.',
        description_urdu: 'کمزور پس منظر کے قانون کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Stipend', 'Books allowance', 'Bar training'],
        benefits_urdu: ['فیس', 'وظیفہ', 'کتابوں کا الاؤنس', 'بار تربیت'],
        application_deadline: '2024-09-10',
        application_url: 'https://pakistanbarcouncil.org',
        contact_info: { website: 'https://pakistanbarcouncil.org' },
        requirements: ['Law admission', 'Financial need', 'Academic merit'],
        requirements_urdu: ['قانون میں داخلہ', 'مالی ضرورت', 'تعلیمی میرٹ'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '5 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor'],
        income_level: ['low'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-22',
        title: 'Pakistan Atomic Energy Commission (PAEC) Scholarship',
        title_urdu: 'پاکستان ایٹمی توانائی کمیشن اسکالرشپ',
        description: 'Scholarships for students in nuclear science and engineering.',
        description_urdu: 'جوہری سائنس اور انجینئرنگ کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Full tuition fee', 'Stipend', 'Research opportunities', 'Job placement'],
        benefits_urdu: ['مکمل فیس', 'وظیفہ', 'تحقیق کے مواقع', 'ملازمت کی فراہمی'],
        application_deadline: '2024-08-25',
        application_url: 'https://paec.gov.pk',
        contact_info: { website: 'https://paec.gov.pk' },
        requirements: ['Nuclear science background', 'Security clearance', 'Academic excellence'],
        requirements_urdu: ['جوہری سائنس کا پس منظر', 'سیکیورٹی کلیئرنس', 'تعلیمی برتری'],
        funding_amount: { min: 100000, max: 300000, currency: 'PKR' },
        duration: '4-6 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-23',
        title: 'Pakistan Space and Upper Atmosphere Research Commission (SUPARCO) Program',
        title_urdu: 'پاکستان اسپیس اینڈ اپر ایٹموسفیئر ریسرچ کمیشن پروگرام',
        description: 'Research and development opportunities in space science and technology.',
        description_urdu: 'خلائی سائنس اور ٹیکنالوجی میں تحقیق اور ترقی کے مواقع۔',
        category: 'employment',
        eligibility_criteria: { education_level: ['bachelor', 'master', 'phd'], location: ['Pakistan'] },
        benefits: ['Research opportunities', 'Stipend', 'Professional development', 'International exposure'],
        benefits_urdu: ['تحقیق کے مواقع', 'وظیفہ', 'پیشہ ورانہ ترقی', 'بین الاقوامی تجربہ'],
        application_deadline: '2024-09-05',
        application_url: 'https://suparco.gov.pk',
        contact_info: { website: 'https://suparco.gov.pk' },
        requirements: ['Space science background', 'Research proposal', 'Academic excellence'],
        requirements_urdu: ['خلائی سائنس کا پس منظر', 'ریسرچ پروپوزل', 'تعلیمی برتری'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '2-4 years',
        location: ['Pakistan'],
        age_range: { min: 20, max: 35 },
        education_level: ['bachelor', 'master', 'phd'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-24',
        title: 'Pakistan Council of Research in Water Resources (PCRWR) Scholarship',
        title_urdu: 'پاکستان کونسل آف ریسرچ ان واٹر ریسورسز اسکالرشپ',
        description: 'Scholarships for students in water resources and environmental studies.',
        description_urdu: 'پانی کے وسائل اور ماحولیاتی مطالعہ کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Research grant', 'Stipend', 'Field work support'],
        benefits_urdu: ['فیس', 'ریسرچ گرانٹ', 'وظیفہ', 'فیلڈ ورک کی مدد'],
        application_deadline: '2024-09-15',
        application_url: 'https://pcrwr.gov.pk',
        contact_info: { website: 'https://pcrwr.gov.pk' },
        requirements: ['Environmental science background', 'Research proposal', 'Academic excellence'],
        requirements_urdu: ['ماحولیاتی سائنس کا پس منظر', 'ریسرچ پروپوزل', 'تعلیمی برتری'],
        funding_amount: { min: 30000, max: 150000, currency: 'PKR' },
        duration: '2-4 years',
        location: ['Pakistan'],
        age_range: { min: 18, max: 30 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-25',
        title: 'Pakistan Standards and Quality Control Authority (PSQCA) Training',
        title_urdu: 'پاکستان اسٹینڈرڈز اینڈ کوالٹی کنٹرول اتھارٹی تربیت',
        description: 'Training programs for quality control and standardization professionals.',
        description_urdu: 'کوالٹی کنٹرول اور معیاری سازی کے پیشہ ور افراد کے لیے تربیتی پروگرام۔',
        category: 'skill_training',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Professional training', 'Certification', 'Industry exposure', 'Job placement'],
        benefits_urdu: ['پیشہ ورانہ تربیت', 'سرٹیفیکیشن', 'انڈسٹری کا تجربہ', 'ملازمت کی فراہمی'],
        application_deadline: '2024-10-05',
        application_url: 'https://psqca.gov.pk',
        contact_info: { website: 'https://psqca.gov.pk' },
        requirements: ['Science/engineering background', 'Professional experience', 'Interest in quality control'],
        requirements_urdu: ['سائنس/انجینئرنگ کا پس منظر', 'پیشہ ورانہ تجربہ', 'کوالٹی کنٹرول میں دلچسپی'],
        funding_amount: { min: 10000, max: 80000, currency: 'PKR' },
        duration: '1-3 months',
        location: ['Pakistan'],
        age_range: { min: 22, max: 45 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium', 'high'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-26',
        title: 'Pakistan Council of Scientific and Industrial Research (PCSIR) Women Program',
        title_urdu: 'پاکستان کونسل آف سائنٹیفک اینڈ انڈسٹریل ریسرچ خواتین پروگرام',
        description: 'Special research opportunities for women in scientific and industrial fields.',
        description_urdu: 'سائنسی اور صنعتی شعبوں میں خواتین کے لیے خصوصی تحقیق کے مواقع۔',
        category: 'women_empowerment',
        eligibility_criteria: { education_level: ['bachelor', 'master', 'phd'], location: ['Pakistan'], gender: 'female' },
        benefits: ['Research opportunities', 'Stipend', 'Professional development', 'Mentorship'],
        benefits_urdu: ['تحقیق کے مواقع', 'وظیفہ', 'پیشہ ورانہ ترقی', 'رہنمائی'],
        application_deadline: '2024-09-20',
        application_url: 'https://pcsir.gov.pk/women',
        contact_info: { website: 'https://pcsir.gov.pk/women' },
        requirements: ['Female scientist', 'Research proposal', 'Academic excellence'],
        requirements_urdu: ['خواتین سائنسدان', 'ریسرچ پروپوزل', 'تعلیمی برتری'],
        funding_amount: { min: 40000, max: 180000, currency: 'PKR' },
        duration: '1-3 years',
        location: ['Pakistan'],
        age_range: { min: 20, max: 40 },
        education_level: ['bachelor', 'master', 'phd'],
        income_level: ['low', 'medium'],
        gender: 'female',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-27',
        title: 'Pakistan Council of Architects and Town Planners (PCATP) Scholarship',
        title_urdu: 'پاکستان کونسل آف آرکیٹیکٹس اینڈ ٹاؤن پلانرز اسکالرشپ',
        description: 'Scholarships for architecture and urban planning students.',
        description_urdu: 'معماری اور شہری منصوبہ بندی کے طلباء کے لیے وظائف۔',
        category: 'scholarship',
        eligibility_criteria: { education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Tuition fee', 'Stipend', 'Studio materials', 'Internship opportunities'],
        benefits_urdu: ['فیس', 'وظیفہ', 'اسٹوڈیو مواد', 'انٹرن شپ کے مواقع'],
        application_deadline: '2024-08-30',
        application_url: 'https://pcatp.org.pk',
        contact_info: { website: 'https://pcatp.org.pk' },
        requirements: ['Architecture/planning admission', 'Portfolio', 'Academic merit'],
        requirements_urdu: ['معماری/منصوبہ بندی میں داخلہ', 'پورٹفولیو', 'تعلیمی میرٹ'],
        funding_amount: { min: 50000, max: 200000, currency: 'PKR' },
        duration: '4-5 years',
        location: ['Pakistan'],
        age_range: { min: 17, max: 25 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-28',
        title: 'Pakistan Council of Research in Water Resources (PCRWR) Youth Program',
        title_urdu: 'پاکستان کونسل آف ریسرچ ان واٹر ریسورسز یوتھ پروگرام',
        description: 'Special opportunities for young researchers in water resources.',
        description_urdu: 'پانی کے وسائل میں نوجوان محققین کے لیے خصوصی مواقع۔',
        category: 'youth',
        eligibility_criteria: { age_min: 18, age_max: 30, education_level: ['bachelor', 'master'], location: ['Pakistan'] },
        benefits: ['Research opportunities', 'Stipend', 'Professional development', 'International exposure'],
        benefits_urdu: ['تحقیق کے مواقع', 'وظیفہ', 'پیشہ ورانہ ترقی', 'بین الاقوامی تجربہ'],
        application_deadline: '2024-09-25',
        application_url: 'https://pcrwr.gov.pk/youth',
        contact_info: { website: 'https://pcrwr.gov.pk/youth' },
        requirements: ['Young researcher', 'Water resources interest', 'Academic excellence'],
        requirements_urdu: ['نوجوان محقق', 'پانی کے وسائل میں دلچسپی', 'تعلیمی برتری'],
        funding_amount: { min: 25000, max: 120000, currency: 'PKR' },
        duration: '1-2 years',
        location: ['Pakistan'],
        age_range: { min: 18, max: 30 },
        education_level: ['bachelor', 'master'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-29',
        title: 'Pakistan Council of Scientific and Industrial Research (PCSIR) Technology Transfer',
        title_urdu: 'پاکستان کونسل آف سائنٹیفک اینڈ انڈسٹریل ریسرچ ٹیکنالوجی ٹرانسفر',
        description: 'Technology transfer and commercialization opportunities for researchers.',
        description_urdu: 'محققین کے لیے ٹیکنالوجی ٹرانسفر اور تجارتی کاری کے مواقع۔',
        category: 'technology',
        eligibility_criteria: { education_level: ['master', 'phd'], location: ['Pakistan'] },
        benefits: ['Technology transfer support', 'Commercialization assistance', 'Patent support', 'Industry connections'],
        benefits_urdu: ['ٹیکنالوجی ٹرانسفر کی مدد', 'تجارتی کاری کی مدد', 'پیٹنٹ کی مدد', 'انڈسٹری کنکشنز'],
        application_deadline: '2024-10-10',
        application_url: 'https://pcsir.gov.pk/tech-transfer',
        contact_info: { website: 'https://pcsir.gov.pk/tech-transfer' },
        requirements: ['Research innovation', 'Technology readiness', 'Commercial potential'],
        requirements_urdu: ['تحقیقی اختراع', 'ٹیکنالوجی کی تیاری', 'تجارتی صلاحیت'],
        funding_amount: { min: 100000, max: 500000, currency: 'PKR' },
        duration: '1-3 years',
        location: ['Pakistan'],
        age_range: { min: 25, max: 50 },
        education_level: ['master', 'phd'],
        income_level: ['low', 'medium', 'high'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    },
    {
        id: 'sch-30',
        title: 'Pakistan Council of Research in Water Resources (PCRWR) Innovation Grant',
        title_urdu: 'پاکستان کونسل آف ریسرچ ان واٹر ریسورسز انوویشن گرانٹ',
        description: 'Innovation grants for water resource management and conservation.',
        description_urdu: 'پانی کے وسائل کی انتظام اور تحفظ کے لیے اختراعی گرانٹ۔',
        category: 'grant',
        eligibility_criteria: { education_level: ['bachelor', 'master', 'phd'], location: ['Pakistan'] },
        benefits: ['Innovation funding', 'Technical support', 'Mentorship', 'Commercialization assistance'],
        benefits_urdu: ['اختراعی فنڈنگ', 'تکنیکی مدد', 'رہنمائی', 'تجارتی کاری کی مدد'],
        application_deadline: '2024-10-15',
        application_url: 'https://pcrwr.gov.pk/innovation',
        contact_info: { website: 'https://pcrwr.gov.pk/innovation' },
        requirements: ['Innovative water solution', 'Feasibility study', 'Impact potential'],
        requirements_urdu: ['اختراعی پانی کا حل', 'عملی مطالعہ', 'اثر کی صلاحیت'],
        funding_amount: { min: 50000, max: 300000, currency: 'PKR' },
        duration: '1-2 years',
        location: ['Pakistan'],
        age_range: { min: 20, max: 45 },
        education_level: ['bachelor', 'master', 'phd'],
        income_level: ['low', 'medium'],
        gender: 'all',
        disability_friendly: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        is_active: true
    }
] 